/**
 * Poster paths and the inline LQIP — HERO_SCENE_SPEC.md §9.1.
 *
 * GENERATED by scripts/capture-posters.mjs; edit that script, not this file.
 */
export const posters = {
  desktop: {
    width: 1920,
    height: 1080,
    unlit: { avif: "/three/posters/f0-unlit-desktop.avif", webp: "/three/posters/f0-unlit-desktop.webp" },
    lit: { avif: "/three/posters/f0-lit-desktop.avif", webp: "/three/posters/f0-lit-desktop.webp" },
  },
  mobile: {
    width: 780,
    height: 1688,
    unlit: { avif: "/three/posters/f0-unlit-mobile.avif", webp: "/three/posters/f0-unlit-mobile.webp" },
    lit: { avif: "/three/posters/f0-lit-mobile.avif", webp: "/three/posters/f0-lit-mobile.webp" },
  },
  lqip:
    "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABQAwCdASoYAA4APu1kqU2ppaOiMAgBMB2JaQAAetDUSZaaAAD+8P82tzMYDiAAAAA=",
} as const;
