#!/usr/bin/env node
/**
 * Bake the Inflexions mark into data the formation generator can sample —
 * CREATIVE_DIRECTION_3D.md §9 Phase 1 item 1 and Phase 4 item 1.
 *
 *   node scripts/bake-mark.mjs
 *
 * Reads public/brand/mark-mask.png (the whole mark, traced from the logo at
 * 2000 px) and public/brand/mark-heat.png (its red parts: the head, the
 * raised arm and the right-hand stroke, as in public/fav.png), downsamples
 * both to a 1-bit grid and writes src/three/core/worker/markData.ts. The
 * generator runs in a worker and in node tests, where decoding images is not
 * available, so the mark travels as a bitmask string.
 */
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const W = 240;

async function bits(file) {
  const { data, info } = await sharp(file)
    .greyscale()
    .resize({ width: W, kernel: "lanczos3" })
    .raw()
    .toBuffer({ resolveWithObject: true });
  const out = new Uint8Array(Math.ceil((info.width * info.height) / 8));
  for (let i = 0; i < info.width * info.height; i += 1) {
    if (data[i] > 127) out[i >> 3] |= 1 << (i & 7);
  }
  return { w: info.width, h: info.height, b64: Buffer.from(out).toString("base64") };
}

const mask = await bits("public/brand/mark-mask.png");
const heat = await bits("public/brand/mark-heat.png");
if (mask.w !== heat.w || mask.h !== heat.h) throw new Error("mask and heat maps differ in size");

const src = `/**
 * The Inflexions mark as 1-bit grids — GENERATED by scripts/bake-mark.mjs
 * from public/brand/mark-mask.png and mark-heat.png. Edit the script, not
 * this file. Row-major, least significant bit first, top row first.
 */
export const MARK_W = ${mask.w};
export const MARK_H = ${mask.h};
export const MARK_MASK = "${mask.b64}";
export const MARK_HEAT = "${heat.b64}";
`;
writeFileSync("src/three/core/worker/markData.ts", src);
console.log(`wrote markData.ts: ${mask.w} x ${mask.h}, ${(src.length / 1024).toFixed(1)} KB`);
